#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset


python manage.py migrate
python manage.py create_local_user_and_admin
python manage.py loaddata subjects.json
uvicorn config.asgi:application --host 0.0.0.0 --reload
